- proc/test_msg.c
Accordingly to phoenix-rtos/libphoenix#70 (comment)
> Unify use of the rid parameter of msgRecv, msgRespond functions

- Makefile
- runner.py
- sample/Makefile
- sample/helloworld/Makefile
- sample/helloworld/test.yaml
- sample/test/Makefile
- sample/test/fails/Makefile
- sample/test/fails/test.yaml
- sample/test/test.yaml
- setjmp/Makefile
- setjmp/test.yaml
- trunner/builder.py
- trunner/config.py
- trunner/device.py
- trunner/test_runner.py
- trunner/testcase.py
- Add 'dir' keyword for config which specifies where test are placed on phoenix-rtos. By default if our path is `/home/user/phoenix-rtos-project/myproject/path/to/test/test.yaml` then test are run from `/bin/myproject/path/to/test/{syspage}`. Using 'dir' keyword we can change default path and run tests from wherever we want.
- Add `install_fs` target to Makefile.
- Decrease pyexpect timeout to 8 seconds
Needed by [ci: add test runner job #61](https://github.com/phoenix-rtos/phoenix-rtos-project/pull/61)
> runner: add 'install' target to Makefile

- .github/workflows/runner-ci.yaml
- psh/test-mkdir.py
- psh/test-ps.py
- sample/test/fails/test-fail-output-1.py
- sample/test/fails/test-fail-output-2.py
- sample/test/test-echo.c
- trunner/builder.py
- trunner/test/test_config.py
Comments to some other warnings:
1. Build on riscv64-virt produces the following warning:
```
unity/unity_internals.h:903:121: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
[omitted output]
sample/test/test-unity.c:26:2: note: in expansion of macro 'TEST_ASSERT_EQUAL_PTR'
26 |  TEST_ASSERT_EQUAL_PTR(p, NULL);
|  ^~~~~~~~~~~~~~~~~~~~~
```
Unity uses `UINTPTR_MAX` to detect pointer size. Then it casts it to int of the right size. In libphoenix `UINTPTR_MAX` is defined as `UINT32_MAX` but `sizeof(void*)` is 8. Also `uintptr_t` is defined as `uint64_t` so it might some inconsistency.  
2. No return warning mentioned in https://github.com/phoenix-rtos/phoenix-rtos-tests/issues/10
It might be triggered because of lack `noreturn` attribute in `longjmp` …
> Add CI for runner. Fix warnings from GCC and flake

- initfini/test.py
- psh/test-mkdir.py
- psh/test-prompt.py
- psh/test-ps.py
- sample/helloworld/test.py
- sample/test/fails/test-fail-output-2.py
- trunner/config.py
- trunner/device.py
- trunner/harness.py
- trunner/test/test_exceptions.py
- trunner/testcase.py
- trunner/tools/color.py
- trunner/tools/text.py
Now we do not have to return error value from harnesses. Test interrupted by assertion produces following exception message:
Test interrupted by python exception other than assertion/pyexpect are handled and marked as failed.
> Add assertion handling

- meterfs/test_meterfs_miscellaneous.c
Added test case for resizing file to size bigger than allowed by sectors number for this file. Change is connected with bug fix PR [#32](https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/32).
> meterfs: added resize test case

- meterfs/test_meterfs_miscellaneous.c
Test case for lookup bug. Bug resolve in PR [#33](https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/33).
> meterfs: added test case for multiple lookup calling

- psh/test.yaml
- runner.py
- sample/helloworld/test.yaml
- sample/test/test.yaml
- trunner/device.py
- trunner/test_runner.py
- trunner/testcase.py
These changes add possibility of running tests automatically. Runner uses new plo to load test ELF (from _boot/test) to the syspage.
Some remarks:
1.  usb0 is not ready when the plo prompt is printed first time. Normally in the initscript there is some wait (like wait 2000), so end user is not affected by this. Unfortunately, plo occasionally crashes executing this command. Therefore, for now, tests will be build without wait in the preinit script and runner will wait 1 second for usb initialization (but maybe is possible to make some lookup for /dev).
2. `phoenixd` needs ~1 second to be ready to handle requests from plo. Here we could parse output from phoenixd and look for the "dispatcher ready" string but `phoenixd` doesn't flush too often. Setting small buffers in `Popen` doesn't …
> runner: imxrt106x: add loading tests using plo

- initfini/main.c
It fixes warning:
```
/github/workspace/phoenix-rtos-tests/initfini/main.c:19:1: warning: constructor priorities from 0 to 100 are reserved for the implementation [-Wprio-ctor-dtor]
```
Priorities for constructor and destructor must be greater than 100. (as gcc says)
> tests: initfini: change constructor priority

- trunner/device.py
Temporary fix: catch RuntimeError on RPi.GPIO import. I don't know right now why new `devel` image raises `RuntimeError` instead of `ImportError` as earlier. One solution might be to move importing RPi.GPIO into `IMXRT106xRunner` class.
> runner: fix RPi import

- .github/workflows/ci.yml
- trunner/config.py
- trunner/device.py
Tests are now installed in the `fs/{target}/root/bin` but are run from `_boot` directory which requires additional copy step in building phase. Instead, run tests directly from the `_fs/{target}` directory.
According to upload-artifacts docs:
> If multiple paths are provided as input, the least common ancestor of all the search paths will be used as the root directory of the artifact.
So we can leave it at is and content of the zip will be following:
```
phoenix-rtos-ia32-generic.zip after unziping:
- _boot/phoenix-ia32-generic.disk
- rootfs-ia32-generic.tar
```
Or we can move `rootfs-ia32-generic.tar` into _boot and then upload directory, so it will looks like:
```
phoenix-rtos-ia32-generic.zip after unziping:
- phoenix-ia32-generic.disk
- rootfs-ia32-generic.tar
```
I have prepared …
> ci: add rootfs to artifacts

- libc/Makefile
- libc/common.c
- libc/common.h
- libc/main.c
- libc/resolve_path.c
- libc/test.yaml
libc unit test framework stub + tests around pathname resolution.
**The tests will fail until all relevant changes in kernel / filesystems / libphoenix will be merged**
Rewriting path handling in `libphoenix`.
**This PR is to be merged only after all other relevant PR will be merged and CI checks for this test would pass**
I would appreciate review anyway.
> libc: unittests for path resolving (`realpath()`, `canonicalize_file_name()`, etc.)

- libc/file.c
- libc/main.c
Bug: phoenix-rtos/phoenix-rtos-project#133
> libc: add test for fclose(stdin)

- psh/test-auth.py
- psh/test-mkdir.py
- psh/test-prompt.py
- psh/test-ps.py
- psh/test-pshlogin.py
- psh/test.yaml
- psh/tools/basic.py
- psh/tools/login.py
Tests added for:
- pshlogin (only ia32)
- auth applet (all arch)
JIRA: PD-75
Two separate tests added as it is now impossible to properly test `pshlogin` on imxrt1064 (it needs binary rename).
- `test-pshlogin.py` tests launching psh with login prompt. It does not test exitability as it needs launching it as a first psh. It is currently only for ia32
- `test-auth.py` is a similar test to `test-pshlogin.py` but it launches login prompt using `auth` command accessible in `psh`. It is a way to test login logic (searching for password etc) works without spawning new `psh`
As `pshlogin` uses `auth` applet not all features are duplicated in `pshlogin` tests, especially in places where there are no concerns of memory usage (e.g backspace handling)
Tests regarding issues with:
- entering correct …
> pshlogin: tests of login utility

- trunner/config.py
Look for `phoenix-rots-project` in path from right to left instead from left to right.
`phoenix-rtos-project` run tests on a self-hosted runner using a path `/github-runner/_work/phoenix-rtos-project/phoenix-rtos-project`. The path should be split after second `phoenix-rtos-project` - not the first one. Knowing that, choose last occurrence of `phoenix-rtos-project`.
> runner: resolve path backwards

- runner.py
- trunner/device.py
JIRA: CI-63
-if test runner starts running tests - blue led is on
-if test runner fails - red led is on
-if test runner succeed - green led is on
It provides information about tests status in rack unit for testing
> add led test state signalling for imxrt106x runner

- libc/resolve_path.c
JIRA: PD-160
According to (https://github.com/phoenix-rtos/libphoenix/pull/117) resolve_path should return NULL if presented a path with missing branch (not missing leaf). This PR changes output expected by test.
> resolve_path: missing_dir should return NULL

- libc/harness/Makefile
- libc/harness/test.yaml
- libc/harness/test_exec.c
- libc/harness/test_exec.py
- psh/tools/basic.py
JIRA: PD-175
add exec functions tests
- create directory harness for harness tests in libc directory
- create text_exec.c, which executes itself using execve, execvpe, and execvp (different test cases)
- create harness test_exec.py, which executes test_exec.c with individual test cases
- add assert_expected function to psh/tools/basic.py
When running busybox tests, there was a suspicion that the execve function was not working properly
> libc: add exec functions tests

- trunner/config.py
- trunner/device.py
JIRA: CI-69
- runner: imxrt106x: change serial port to usb socket reference
- runner: imxrt106x: add _restart_by_poweroff procedure
- runner: imxrt106x: rename boot to reboot, add _restart_by_poweroff to it and add double reboot to load method
- runner: imxrt106x: decrease waiting for dev time step value
- runner: add power_usb_ports(enable: bool) function for power on and off rpi ports
- runner: add unbind_rpi_usb(port_address) function and DEVICE_SERIAL_USB const for port address
It's for running each test on fresh mimxrt1064 eval kit (after power down and power up)
> runner: imxrt106x: add relay restart

- runner.py
- trunner/config.py
- trunner/runners/HostRunner.py
- trunner/runners/IMXRT106xRunner.py
- trunner/runners/STM32L4Runner.py
- trunner/runners/common.py
- trunner/test/test_config.py
- trunner/test/test_exceptions.py
- trunner/testcase.py
JIRA: SKAL-193
Added two new features to runner:
- `--baudrate` commandline option specifying the serial communication speed
- `psh` yaml property which if runner should expect psh to appear on serial connection
- `--baudrate`:
- Some future test targets can have multiple serial speed connections, so this may be handy for development purposes.
- For full configuration there should be options for parity bits/stop bits etc. but this should be done when those config options will be moved to some _yaml_ config file
- this change should not be necessary for full CI, but rather for development of new runners, together with project specific runners
- `psh`:
- some tests or test targets may not run through `psh` shell so it should be possible to specify it
> runner: `--baudrate` option and `psh` yaml property

- psh/test-cat-shells.py
- psh/tools/README.md
- psh/tools/psh.py
JIRA: PD-77
disable matching `EOL` after expected output when passing regex to `assert_cmd()` function in psh test module
Finally it's easier to match multi line output using regex when matching last `EOL` is disabled.
> psh: change behaviour when passing regex to assert_cmd in psh test module

- psh/tools/README.md
- psh/tools/psh.py
Small changes in psh test module (does not affect existing tests):
- fix assert_exec function in psh module (the function hasn't been used before)
- handle passing empty string and tuples in `expected` argument in assert_cmd function
- small corections in README.md for psh test module
- pass pexpect.EOF to `pexpect.expect` in order to print assertion message when EOF occured
JIRA: PD-77
> psh: tools: handle empty string and lists in assert_cmd expected argument and other small corrections for psh test module

- trunner/runners/ARMV7M7Runner.py
- trunner/runners/common.py
- runner: adapt to automatic go! command sending in plo
Target solution is sending go! command in plo automaticly.
This change will make it possible and will work for current configuration too.
JIRA: CI-103
> runner: adapt to automatic go! command sending in plo

- meterfs/test_meterfs_writeread.c
JIRA: DTR-179
In DTR-179 meterfs record overhead was increased from 4 to 8 bytes (to accommodate checksum). This caused one test to fail - not sufficient number of sectors was allocated for a file
> meterfs: Adapted to bigger record overhead (4 -> 8 bytes)

- runner.py
- trunner/device.py
- trunner/runners/ARMV7M7Runner.py
- trunner/runners/HostRunner.py
- trunner/runners/IMXRT106xRunner.py
- trunner/runners/IMXRT117xRunner.py
- trunner/runners/QemuRunner.py
- trunner/runners/STM32L4Runner.py
- trunner/runners/common.py
- trunner/test_runner.py
JIRA: CI-107
Add functionality to "-l debug" option of runner so that it dumps everything that was read into a file in /tmp/ directory
For inspection purposes runner should have an option to dump everything it has read from target device.
> runner: full log dump after "-l debug" option

- psh/test-auth.py
- psh/tools/login.py
DONE: CI-114
Fix waiting for psh prompt in login test
Fixture:
-`auth` applet, after passing empty password shall wait 1 second and then close, effectively going back to psh (showing psh prompt)
- `assert_login_fail()` uses `assert_prompt_fail()` which guarantees that for given time (1 second here) psh prompt **doesn`t** appear on screen
- after that the new test commences where `auth` is written into console
If psh prompt appears a liitle bit late than 1s, the test can already assert its absence and immediately write `auth` to console which will be written into _nothing_ as the command interpreter is not yet present. Thus it fails next test case which thinks it properly called `auth` command when it did not.
> tests: auth timing loophole fix

- trunner/builder.py
- trunner/runners/HostRunner.py
- trunner/runners/QemuRunner.py
- trunner/runners/common.py
- trunner/test/test_exceptions.py
- trunner/testcase.py
> runner: catch unicode error

- libc/main.c
- libc/unistd_getopt.c
JIRA: CI-100
adding tests of libphoenix unistd.h function `getopt()` checking its POSIX compliance and checking for its operability
Bringing POSIX compliance to libphoenix functions from unistd.h library
> tests-libc: adding tests of unistd.h getopt() function

- libc/main.c
- libc/unistd_uids.c
JIRA: CI-100
- Adding tests of functions from unistd.h that cope with processes `pid`s and `uid`s
- Couple IGNOREs as couple issues were found.
Issues related to these tests:
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/279
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/280
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/282
> tests-libc: add tests of pid/uid related functions in unistd.h

- meterfs/test_meterfs_writeread.c
Adding read with non-zero offset to meterfs tests
Reading files with non-zero offset fails on current meterfs due to checksum calculation error. This problem was introduced in https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/61
> meterfs: test partial record read

- psh/test-ps.py
- trunner/device.py
- trunner/runners/QemuRunner.py
- trunner: add using testing script for launching ia32-generic emualtor
- psh: handle programs with arguments in test-ps
JIRA: CI-116
Now the command for running qemu (ia32-generic target) is now placed strictly in test runner:
It may be better to create the proper script in `scripts` directory that could be used by a test runner. If there is a need for change in qemu running it will be done only in the `scripts` directory (it's easier to remember about changing similar script in the same directory than changing some file in tests repository).
After enabling testing script the lwip with arguments will be present in ps output and `ValueError` will occur. The second commit fixes it.
> use ia32 generic testing script and handle programs with arguments in test-ps

- busybox/Makefile
- busybox/test_busybox.c
- busybox/test_busybox.yaml
- runner.py
- trunner/config.py
- trunner/harness.py
- trunner/test_runner.py
- trunner/testcase.py
JIRA: RTOS-59
- busybox: add running busybox testsuite
- busybox: add a check if the test suite is in the bin directory
- busybox: add strerror and _exit from child process when failed 
- busybox: add posixsrv exec error handling 
- busybox: allow test_busybox to be run using test runner as single test 
- busybox: add long_test argument for runner to allow running busybox test suite
- busybox: temporarily disable check if posixsrv has been run properly, because of waitpid WNOHANG problem
- busybox: add export bindir variable, because of test suite location change
- busybox: allow to run each busybox command tests seperately using test runner
- runner: add alternative option for disabling long tests, check long_test arg earlier
Test_busybox runs a busybox testsuite (which is copied to …
> busybox: add running busybox testsuite

- psh/test-mkdir.py
- psh/test.yaml
- psh/tools/psh.py
- trunner/config.py
- trunner/device.py
- trunner/runners/QemuRunner.py
- trunner/testcase.py
- runner: add armv7a9-zynq7000-emu implementation
- psh: disable asserting ownership in mkdir test and enable the test on dummyfs targets
- psh: test-mkdir: divide fname with all chars
JIRA: CI-110
JIRA: CI-120
> runner: add armv7a9-zynq7000-emu implementation and enable test-mkdir for imxrt targets

- psh/test-ls-rootfs.py
- psh/test_ls.py
- trunner/runners/QemuRunner.py
- trunner/runners/common.py
- trunner/testcase.py
- psh: ls: move size test case to test-ls-rootfs
- psh: ls: make -f arg case more flexible
- trunner: adapt timeout and encoding to a new armv7a9-zynq7000
- Default timeout for pyexpect was too low for jffs init on armv7a9-zynq7000-qemu
- Because of non-ascii character in init logs (©) switch back to utf-8 encoding in psh
- -f argument test case assumed that not sorted files are listed by creation time, which is wrong for jffs. Checking files order in this case has been disabled.
- The correction of size sorting was checked by listing an empty file and an empty directory.
Assumption that directory has larger size than a file is wrong for jffs.
Now size size sorting assertion is done by comparing empty file with psh binary in /bin.
> adapt test runner and ls tests to a new armv7a9-zynq7000

- psh/test.yaml
- psh: disable psh tests for armv7a9-zynq7000-qemu
DONE: PD-288
After adding busybox to armv7a9-zynq7000 target psh isn't run by default.
It's the temporary solution before adding support for running psh from ash.
> psh: disable psh tests for armv7a9-zynq7000-qemu

- libc/main.c
- libc/wchar.c
- libc: add wcscmp function tests 
Covering `wcscmp()` implementation.
JIRA: PD-285
> libc: add wcscmp function tests

- proc/test.yaml
- proc/test_priority.py
- trunner/config.py
- trunner/runners/ARMV7M7Runner.py
- trunner/test/test_config.py
- trunner/testcase.py
DONE: CI-109
- execute and assert test_priority in a python harness test
- trunner: add syspage yaml property to allow loading binaries without executing it
Simple solution that plugs test_priority into CI. For now there is no possibility to get return code from executed binary, so there is a temporary alternative option.
> add running test_priority in CI process and syspage yaml property to trunner

- micropython/test_micropython.c
This PR contains small adjustments in MicroPython tests.It gets rid of warnings during compilation of `test_micropython.c` file.
More elegant code.
> MicroPython: getting rid of warnings during compilation MicroPython tests

- libc/pthread_cond.c
JIRA: RTOS-236
fix return values from pthread library
- JIRA: RTOS-236
> pthread_cond: fix return values

- trunner/runners/common.py
- trunner: plo: switch to sending CR instead of CRLF
- trunner: remove baudrate arg for phoenixd
- There were issue, where LF was left in the buffer, because plo parsed only CR
- Baudrate arg is no longer needed
JIRA: PD-306
JIRA: PD-307
> trunner: plo: switch to sending CR instead of CRLF, remove baudrate arg for phoenixd

- psh/test-auth.py
- psh/test-autocompletion.py
- psh/test-cat-shells.py
- psh/test-cat.py
- psh/test-echo.py
- psh/test-gibber.py
- psh/test-history.py
- psh/test-kill.py
- psh/test-ls-rootfs.py
- psh/test-ls.py
- psh/test-mkdir.py
- psh/test-prompt.py
- psh/test-ps.py
- psh/test-pshlogin.py
- psh/tools/README.md
- psh/tools/psh.py
- psh: apply deinit function in psh tests
- psh: improve test-kill after last changes
- psh: provide deinit function in psh test module
- psh: switch to spawning new psh, when starting each psh test
- There were some issues related to previous implementation (e.g. failing test-auth during ~1/n test runner campaigns).
- This is necessary to allow running tests in a row without restart (incoming QuickRunners) and for running psh tests in other other shells, like busybox ash (zynq-qemu tests)
> improve initialization and add deinitialization in psh tests

- libc/unistd_getopt.c
- libc: add new test cases to the getopt
- JIRA: PD-305
> libc: add new test cases to the getopt test 

- libc/main.c
- libc/stdio_file.c
Make test-libc host/POSIX compliant.
> test-libc: correct stdio_file.c to run on host

- psh/test-touch-rootfs.py
- psh/test-touch.py
- psh/test.yaml
- psh/tools/README.md
- psh/tools/common.py
- psh/tools/psh.py
- psh: touch: move rootfs cases to separate test
- psh: enable psh rootfs tests on zynq7000 target
- psh: fix naming in test-touch
- The case with hardlinks was named improperly (they were called symlinks)
- The hardlinks testcase was executed on non-rootfs targets
- Because of using `value` instead of `exclude` rootfs targets were not executed on `zynq7000-zedboard` target
> psh: test-touch fixes, enabling psh rootfs-tests on zynq7000-zedboard

- libc/getpw.c
- libc/unistd_uids.c
- libc: make getpw.c host compatible
- libc: make unistd_uids.c host/POSIX compatible 
- JIRA: PD-321
> libc: make getpw.c host compatible

- libc/main.c
- libc/unistd_file.c
- Adding tests of file related functions from libphoenix unistd.h library:
- close()
- read()
- write()
- lseek()
- truncate()
- ftruncate()
- dup()
- dup2()
- making some variables in unistd_fsdir.c static so they do not interfere with same-named variables in unistd_file.c 
Expanding _tests-libc_ suite
Issues found:
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/360
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/361
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/362
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/363
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/364
> unistd: tests for file related functions

- libc/stdio_file.c
One of tests in stdio_line had memory leak
> fix memory in libc tests

- psh/test-history.py
- psh/test.yaml
- psh: enable missing tests on armv7m4-stm32l4x6-nucleo
- psh: switch to constant set of tested commands in test-history
JIRA: CI-240
New psh command implemented, which should have been added to omitted in the previous approach.
https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/171
> psh tests improvements

- trunner/harness/unity.py
Changed regex to parsed OK or FAIL after word IGNORED
Parsing before changes:
Parsing after changes:
> trunner: fix parsed unity result

- trunner/harness/unity.py
- trunner: clean unity harness
- trunner: print more details in unity harness error message
The following error found (hard to reproduce): 
Code cleanings
> trunner: improve unity harness

- runner.py
- trunner/config.py
- trunner/harness/pyharness.py
- trunner/host.py
- trunner/types.py
Add `add_to_context` method in the Host class to allow to change the runner context by host instance. It can be useful in runner extensions. For example, host can read environment variables and add them to context kwargs that later can be used in tests.
Add new keyword to yaml config named kwargs. Kwargs should be a dict, similar to python **kwargs parameter. It can be useful to define custom values in yaml config that later can be read in tests. Kwargs for test are merged with kwargs passed using `--kwargs` flag. If there is the same key in both kwargs dicts then runner choose one from the context.
Definiton of the harness that uses `**kwargs`:
```
def harness(dut, **kwargs): ....
def harness(dut, ctx, **kwargs): ...
```
> trunner: host can modify runner context

- meterfs/common.c
- meterfs/file.h
- meterfs/file_pc.c
- meterfs/file_phx.c
- meterfs/test_meterfs_allocate.c
- meterfs/test_meterfs_miscellaneous.c
- meterfs/test_meterfs_openclose.c
- meterfs/test_meterfs_writeread.c
JIRA: RTOS-346
Add path to meterfs prefix to functions.
Add validation to argv[0].
Fix wrong paths.
Tests were assuming that the mount path of meterfs was `/`.
https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/90/files
> Fix meterfs tests on imx6ull

- unity/unity.c
JIRA CI-271
When  TEST_ASSERT_EQUAL_X_ARRAY  fail in specific cases this was printed on output :
After changes is:
> Fix parsing unity fail output when using TEST_ASSER_EQUAL_X_ARRAY

- busybox/busybox.py
- busybox/test_busybox.yaml
- mbedtls/mbedtls.py
- mbedtls/test.yaml
- micropython/micropython.py
- micropython/test_standard.yaml
Activate tests that can be run on targets that are build using the "ports" argument. If specific ports are not built by default (e.g embtls) then target is not included in yaml config. Fix a few things in micopython harness.
> nightly tests: fix ports tests

- busybox/test_busybox.yaml
JIRA: CI-286
Turning off busybox tests to further investigation on targets and why they failed. 
Target excludes for tests:
- ia32-generic-qemu: 
- **uniq, tr, test, tail, sort, readlink, ls, find, diff, cp**
- armv7a9-zynq7000-qemu & armv7a9-zynq7000-zedboard: 
- **bzcat, gzip, ln**
> tests: ignore failing long busybox tests 

- ioctl/Makefile
- ioctl/test-ioctl.c
- ioctl/test.yaml
> add ioctl test

- psh/test-ls-rootfs.py
- psh/tools/common.py
1. psh: improve pshcmds case in ls-rootfs test
2. psh: improve SEPARATOR_PATTERN regex
1. The previous implementation may have parsed binaries that only include searched
phrase.
For example stty (busybox applet) was counted as tty binary.
2. Without this improvement it may have skipped some data during parsing.
> test-ls-rootfs improvements

- libc/string/main.c
- libc/string/string_lenchr.c
Added strcspn and strspn test cases
JIRA: CI-232
> libc: strchr tests: add test group for ASCII compare

- libc/printf/stdio_printf.c
Issue:
The following test cases have an extended execution time:
TEST(stdio_printf_cspn, c_ascii)
TEST(stdio_printf_cspn, c_non_ascii)
TEST(stdio_printf_cspn, s_ascii)
> libc: fix nightly nucleo fail

- libc/string/string_lenchr.c
Tests of functions "*chr" needed additional test case for more probability coverage.
JIRA: CI-211
https://github.com/phoenix-rtos/libphoenix/pull/254
> libc: string.h: Fixed lack of test coverage for stop point as INT

- libc/misc/stat.c
> libc: stat tests improvements

- libc/string/main.c
- libc/string/string_cmp.c
- libc/testdata.h
Added 
*    memcmp(),
*    strcmp(),
*    strncmp(),
*    strcoll()
function tests.
JIRA: CI-231
> libc: string.h: add cmp functions tests

- trunner/tools/phoenix.py
trunner: check the solution using vid, pid instead of device name for plo
JIRA: CI-304
> trunner: phoenixd usb lookup

- trunner/test_runner.py
> trunner: run tests alphabetically

- psh/test-ls-rootfs.py
Adds `clear` and `reset` commands to pshapp internal commands.
On large targets, these commands should be implemented by alias to [`tset`](https://linux.die.net/man/1/tset) provided by system tools, while on small targets where `psh` is used, there `pshapp` controls the terminal (termios) directly, therefore these commands have been implemented as internal (pshapp builtins) and are be available only in the pShell.
JIRA: RTOS-561
The reason for the change is due to the pull-request:
https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/185
And these CI errors:
https://github.com/phoenix-rtos/phoenix-rtos-utils/actions/runs/5895710196/job/15992106606?pr=185#step:6:1803
https://github.com/phoenix-rtos/phoenix-rtos-utils/actions/runs/5895710196/job/15992106787?pr=185#step:6:1828
> psh: ls-rootfs: add `clear`, `reset` internal commands

- trunner/dut.py
- trunner/harness/psh.py
- trunner/test_runner.py
- trunner: treat flashing as a test to include in results export
- especially useful when failed
- we can monitor device flashing performance
- trunner: ensure all logs from previous test are read before starting next one
- trunner: move results exporting to separate functions
- trunner: debug dump invalid XML to file on XML encoding error
Needed to fine-tune XML creation (improve escaping of messages).
JIRA: CI-330
> trunner: xml export / log streaming improvements

- psh/test-cat.py
Flexible regex to not block merge phoenix-rtos/phoenix-rtos-utils#187.
In a separate PR, the cat tests will be extended due to their currently poor version
JIRA CI-336
> psh: cat test regex flexibility

- requirements.txt
- trunner/harness/psh.py
- trunner/test_runner.py
- trunner: fix detecting psh prompt after reboot
- trunner: remove extra newline between tests
- trunner: requirements: bump pytest version
6.2.3 -> 7.4.1
> trunner: remove extra newline + fix prompt detection + bump deps

- trunner/test_runner.py
We want CI to work.
JIRA: CI-331
> trunner: fix sending extra `\n` on 117x target

- psh/test-date.py
- psh/test.yaml
JIRA: PD-249
Tests of `date` psh applet
These tests were written alongside with `date` applet which is under review here:
- https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/123
This is a try of __Test Driven Developement__ procedure application for me.  
- https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/123
> psh: add `date` command tests

- trunner/target/armv7m7.py
JIRA: CI-341 
https://github.com/phoenix-rtos/phoenix-rtos-project/issues/580 solved
> trunner: remove rebooting before each test (imxrt117x)

- trunner/target/armv7a7.py
Changed timeout for jffs2 command based on phoenix size after nightly build (~16MB) and MT25QL256 documentation (max 1s/64KB erase)
Our boards are equipped with MT25QL256 NOR 
From manufacturer documentation, we can decode the size of it (32Mb) 
Manufacturer inform users about `Sector erase time` (This time is given for 64kb of data) 
that means in the worst scenario, it will erase 512 seconds(8.5 minutes).
We divided this value in half and add time which is needed for setting up clean markers, because nightly campaign right now weight exactly half of its space.
> trunner: armv7a7-imx6ull: Increase jffs2 command timeout

- psh/test-autocompletion.py
JIRA: CI-352
When sending TAB after `ls testenv/loremipsum/` the content of directory including prompt is printed, then we send ENTER and it's printed second time. In the previous implementation only the first prompt was asserted and exit (called at the end of test) could have been sent during printing the content (which caused some errors):
> psh: assert missing prompt in the autocompletion test

- libc/Makefile
- libc/scanf/stdio_scanf.c
- libc/stdio/main.c
- libc/stdio/stdio_scanf.c
- libc/test.yaml
JIRA: CI-356 
Enabled test because of fix :  Scanf doesn't read 0x0 as null pointer #677
> libc: scanf: re-enable issued cspn_ptr test

- psh/test.yaml
> riscv64: ignore part of psh tests 

- psh/test-touch-rootfs.py
- psh/tools/common.py
- psh/tools/psh.py
`ls -l` command currently always prints the modification time in `HH:MM` format. These changes allow for modification year in `YYYY` format to be printed instead of the time if the modification year is different from the current year.
This change is compatible with current version of `psh` and doesn't break existing tests.
Fixing https://github.com/phoenix-rtos/phoenix-rtos-project/issues/552 would result in current tests not passing because `ls -l` would be printing the modification year sometimes.
> psh: fixed tests to allow year printing in `ls -l`

- psh/test-autocompletion.py
- psh/test-cat.py
- psh/test-touch.py
- psh/test.yaml
> psh: tests improvements

- psh/test.yaml
Restore tests of `touch` command after https://github.com/phoenix-rtos/phoenix-rtos-project/issues/621 has been fixed.
https://github.com/phoenix-rtos/libphoenix/pull/294 needs to be merged first, because it fixes the bug that causes this test to fail.
> psh: restore tests of touch command

- psh/test-auth.py
- psh/test-pshlogin.py
- psh/test.yaml
- psh/tools/login.py
As the sleep in psh_run() will be increased, this change is needed.
JIRA: CI-361
https://github.com/phoenix-rtos/phoenix-rtos-project/issues/860
> psh: increase login timeout to 2s + fixes in test-auth

- psh/test-touch-rootfs.py
- psh/test-touch.py
- psh/tools/common.py
- psh/tools/psh.py
- psh: assert devs mtimes right after touch in touch tests
- psh: icrease timeout for ls on bin dir in touch-rootfs test
1.
The mtime of some devices (for example /dev/console) may change.
The previous approach asserted modification times of the the whole directory after touching all the files, which took some time.
Within this period of time files could have been accessed by another process.
2.
On zynq7000-qemu target the execution time of ls on this directory right after system startup is increased.
> fix touch tests

- trunner/harness/plo.py
- trunner/target/armv7a7.py
- trunner/target/armv7a9.py
- trunner/test_runner.py
Changed approach how are determined problems with erase with jffs2.
JIRA: CI-375
> trunner: assert jffs2 via output instead of time

- psh/test-help.py
- psh/test.yaml
psh: add help command test
JIRA: PD-77
> psh: add help command test

- trunner/harness/base.py
- trunner/tools/phoenix.py
- trunner: apply delay after soft reset
- trunner: remove workaround with sleep in phoenix.py
plo usb device disappears after some time, not at once after the reset, especially on imxrt117x target
> introduce sleep afer soft reset

- libc/pthread/main.c
- libc/pthread/pthread.c
JIRA: RTOS-671
add tests for `pthread_cleanup`
> libc/pthread: add tests for pthread_cleanup

- busybox/busybox.py
- mbedtls/mbedtls.py
- trunner/types.py
- mbedtls: fix measuring test duration
The subtest result was incorrectly "finished" (added to result) one line after
the result (so actually computed the time of the next test).
Use simplified API to add optional test message to the correct subtest
- trunner: make subresult API more robust
- remove add_subresult_obj() as it's misleading (doesn't add by reference,
just by value
- make add_subresult() return the subresult object which can be updated at a
later time
phoenix-rtos/phoenix-rtos-project#877
> mbedtls|busybox: fix measuring test duration (trunner API change approach)

- libc/stdio/stdio_file.c
- libc/string/string_cmp.c
- libc/string/string_cpy.c
- libc/string/string_lenchr.c
- libc/string/string_tokpbrkstr.c
JIRA: CI-386
Fixes: phoenix-rtos/phoenix-rtos-project#920
> libc: Add missing asserts for malloc

- disk/test_disk.c
JIRA: RTOS-747
On riscv64, `uint64_t` is defined as `unsigned long`, not `unsigned long long`.
> test_disk: fix format warning on riscv64

- trunner/target/emulated.py
JIRA: RTOS-734
Support for rootfs on `riscv64-generic-qemu` has been added.
Test PR: https://github.com/phoenix-rtos/phoenix-rtos-project/pull/987
> trunner: riscv64: enable rootfs

- waitpid/test_waitpid.c
Dynamically linked binaries take longer to startup hence time increase is needed.
Add missing return to main in exec_sum_process path.
JIRA: RTOS-744
> waitpid: increase wait time

- libcache/libcache_utils.c
- libcache/libcache_utils.h
- libcache/test_libcache.c
needed for https://github.com/phoenix-rtos/phoenix-rtos-build/pull/181
> libcache: remove variable declarations from header

- requirements.txt
JIRA: CI-249
This python module gives access to backend of USB device pointed via VID and PID. Also, it gives access to completely reset device. 
In case of use, phoenixd with 100% success rate on sparcv8leon3-gr716-mimas is needed to restart USB converter responsible for this connection. It will guarantee that buffer from either USB Converter and from Mimas will be clear. And without any additional options used by connection. (It may have additional value in case of targets like imxrt 117x nad 106x).
> requirements: add library to detect & reset USB devices

- trunner/test_runner.py
for example: 
- ull
- imx106x:
for example: 
- ull
- imx106x:
> trunner: change style of printing flash output

- requirements.txt
Also: remove non-direct dependencies, bump some of the versions.
JIRA: CI-451
We don't want to install `RPi.GPIO` module on host (it's useless and requires other dependencies).
> trunner: requirements: install RPi.GPIO only on ARM targets

- trunner/harness/plo.py
JIRA: CI-432
In case of 'waiting for input' we interrupt PSH loading. We need to wait a bit to be sure that in this case will be able to do this on faster host environments where this can occur a race condition between sending command and non-accessible input collector.
> trunner: wait for possible plo interruption

- libc/misc/main.c
- libc/misc/unistd_file.c
JIRA: RTOS-882
Add simple tests for `libphoenix` internal `__safe_read/write` functions.
> libc/misc: add tests for libphoenix __safe_read/write functions

- trunner/target/armv7a9.py
- trunner/tools/phoenix.py
> trunner.tools: fix error message in wait_for_vid_pid()

- psh/test.yaml
- psh/tools/psh.py
- trunner/target/armv7m7.py
> psh: enable test execution in new psh for imxrt117x

- psh/test.yaml
It is enabled due to the following issue resolution: phoenix-rtos/phoenix-rtos-project#1097
JIRA: CI-461
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/599
> psh: enable touch/exit test on imxrt117x

- trunner/target/armv7m7.py
JIRA: CI-500
New revision of board use different vendor / product ID for DAP link. To make sure that we select proper USB device, we need to change finding raw VID/PID to "CMSIS-DAP" (On both revision this word can be used to determinate which one is DAP link USB device)
> trunner: imxrt117x unify DAP link device search

- Makefile.sparcv8leon3
- psh/test.yaml
- runner.py
- trunner/target/__init__.py
- trunner/target/emulated.py
JIRA: CI-474
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/1168
> trunner: add sparcv8leon3-generic-qemu target support

- libc/stdio/stdio_file.c
The test case checks fully buffered mode. Previous implementation required data overflowing the buffer (sending 10 bytes when a buffer is 8 bytes long) to be written to a file at once which is not required by POSIX. The current solution forces flushing the remaining 2 bytes anyway
JIRA: CI-507
> libc: fix setvbuf_fullbuffer_overflow testcase

- mem/test_mprotect.c
pages_in_child_copied test checks if pages with protection changed to read from read-write by mprotect are copied by child.
JIRA: RTOS-953
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/608
> test_mprotect: test if mprotected pages are copied

- libc/socket/unix-socket.c
Adds tests of accept, connect, recv(MSG_PEEK)
JIRA: RTOS-862, RTOS-877
Adds unix socket accept/connect tests, both blocking and non-blocking, as well as a small test for proper recv(MSG_PEEK) behavior. 
ia32-generic-qemu
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/572
https://github.com/phoenix-rtos/libphoenix/pull/388
> libc/socket: add unix socket tests

- libc/Makefile
- libc/poll/poll.c
JIRA: RTOS-945
https://github.com/phoenix-rtos/libphoenix/pull/388
> libc/poll: add select() errno test

- libc/socket/unix-socket.c
- libc/stdio/main.c
- libc/stdio/stdio_file.c
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/579
https://github.com/phoenix-rtos/libphoenix/pull/376
> add additional tests for file stream and Unix sockets functionality

- libc/stdlib/stdlib_strto.c
Also add test for strtol, etc. to test for case where "0x" prefix is not followed by a hex digit.
Re-enable tests after fixes in https://github.com/phoenix-rtos/libphoenix/pull/381
> libc: re-enable tests for strtoll, strtoull

- trunner/harness/base.py
- trunner/target/armv7a9.py
- trunner/target/armv7m4.py
- trunner/tools/__init__.py
- trunner/tools/gdb.py
Adds possibility to reset target using jtag standard
> trunner:implement new type of reboot

- lsb_vsx/Makefile
- lsb_vsx/lsb_vsx.py
- lsb_vsx/run-test.c
- lsb_vsx/test.yaml
Add program to execute posix test suite
> Add posix tests (waiting for lsb_vsx port merge)

- libc/scanf-advanced/stdio_scanf_advanced.c
`hhx` format specifier was used with `int` type in test `modifiers_mix,` which is incorrect. This caused the test to fail on big endian architectures (SPARC), as the value was written to the wrong address - the most significant byte. Type was changed to `unsigned char` to be compatible with the specifier.
> libc/scanf-advanced: fix type usage

- devices/grlib-multi/test-grlib-multi.c
- libc/scanf-advanced/stdio_scanf_advanced.c
- libc/stdlib/stdlib_strto.c
- disable tests failing on SPARC FPU because of no support for denormalized numbers
- add GR740 support in test-grlib-multi
- https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/389
- https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/632
- https://github.com/phoenix-rtos/phoenix-rtos-project/pull/1260
- https://github.com/phoenix-rtos/libphoenix/pull/401
- https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/143
- https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/230
- https://github.com/phoenix-rtos/plo/pull/375
- https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/532
- https://github.com/phoenix-rtos/phoenix-rtos-build/pull/222
- https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/143
> add support for gr740

- busybox/busybox.py
- trunner/types.py
>  trunner: improve formatting of multi-line subresult messages 

- trunner/config.py
- trunner/types.py
Some tests need to parse the command or its arguments themselves, so the appropriate field has to be passed to the harness.
JIRA: CI-584
> trunner: make kwargs have test name and cmd by default 

- trunner/target/emulated.py
JIRA: CI-397
In order to implement tests that check psh control capability, we need to run QEMU without ability to call QEMU controls.
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/997
> Using armv7a9-zynq7000-qemu startup script without qemu control
