psh/test-mkdir.py
psh/test-prompt.py
psh/test-ps.py
psh/test.yaml

Some few examples how tests for psh can be made.

tests: add a few tests of psh

---

trunner/test/test_exceptions.py

Additional tests to cover all exception types that can be raised during execution of harness.

runner: add tests for pyexpect exceptions handling

---

Makefile
Makefile.arm
Makefile.armv7
Makefile.common
Makefile.host
Makefile.ia32
Makefile.riscv64
disk/Makefile
fs/Makefile
initfini/Makefile
mem/Makefile
meterfs/Makefile
meterfs/common.h
proc/Makefile
sample/Makefile
sample/helloworld/Makefile
sample/test/Makefile
sample/test/fails/Makefile
setjmp/Makefile
stdio/Makefile
unity/Makefile
virtio/Makefile

Rewrote Makefiles according with the new convention
JIRA: CI-45

makes: use templates for binaries and static libs compilation

---

trunner/device.py

- improve `phoenixd` handling
- add temporary fix due to lack of the `wait` command in plo running from RAM
- move `RPi.GPIO` import to `GPIO` class: https://github.com/phoenix-rtos/phoenix-rtos-project/issues/123

Minor changes in phoenixd handling

---

.github/workflows/ci.yml
libc/test.yaml
proc/test.yaml
psh/test.yaml
sample/helloworld/test.yaml
sample/test/fails/test.yaml
sample/test/test.yaml
trunner/config.py
trunner/device.py

1. Add `armv7m7-imxrt106x` to default targets
2. Change targets of `sample/test/fails` to empty list. These tests are for users to check how fails are handled by the runner. Thanks to that, unnecessary`skipped` logs will not be produced.
3. Increase sleep time before flash from 1 to 2 seconds.
4. Add job for running hardware tests.

runner: move armv7m7-imxrt106x to default targets

---

trunner/device.py

1. Add waiting for the plo port.
2. Run psu using pyexpect (same as phoenixd). Thanks to that we have stderr logs in good order.
CI fails due to bug in https://github.com/phoenix-rtos/phoenix-rtos-project/commit/f03b583b27fbb7de1c80d7fa4bad61c6359aa42b -- probably is associated with the plo alignment. I'm going to rerun CI as soon as bug will be fixed.

runner: imxrt106x: add waiting for usb0 dev

---

trunner/testcase.py

JIRA: RTOS-74
A change to both sysexec (psh) command and proc_syspageSpawnName() which allows to run syspage programs with the default memory map (dmap) set in plo using the app command.
The change is necessary and relates to:
https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/80
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/222
https://github.com/phoenix-rtos/phoenix-rtos-doc/pull/12
https://github.com/phoenix-rtos/phoenix-rtos-doc/pull/12
https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/80
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/222

runner: allow sysexec to spawn programs with default map

---

fs/test_fcntl.c
gfx/test_graph.c
proc/test_msg.c
proc/test_pthreads.c

JIRA: RTOS-77
minor fixes in test_fcntl.c, test_msg.c and test_graph.c

remove warnings

---

fs/test_fcntl.c

Changes required for LFS (Large Files Support):
- changed `%ld` to `%lld` for printing `off_t` type (it's `long long` now),
[JIRA: DTR-103](https://jira.phoenix-rtos.com/browse/DTR-103)
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/240
https://github.com/phoenix-rtos/libphoenix/pull/133
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/141/
https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/46
https://github.com/phoenix-rtos/phoenix-rtos-lwip/pull/43/
https://github.com/phoenix-rtos/phoenix-rtos-posixsrv/pull/8
https://github.com/phoenix-rtos/phoenix-rtos-usb/pull/13
https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/92
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/199

Adapt to Large Files Support changes

---

trunner/device.py

JIRA: CI-88
- add is_cut_power_used attribute to IMXRT106xRunner class
- set default restart by jtag use
In one of the test units some problem with flashing board has been occurred (when using restart by power off). Otherwise restart by jtag would be a better solution for fast ci (triggered by pr's and merges to master), and restart by power off would be better for long tests scheduled for night hours.

runner: imxrt106x: switch to restart by jtag

---

libc/harness/test.yaml
libc/test.yaml
psh/test.yaml
runner.py
trunner/config.py
trunner/device.py
trunner/runners/ARMV7M7Runner.py
trunner/runners/HostRunner.py
trunner/runners/IMXRT106xRunner.py
trunner/runners/IMXRT117xRunner.py
trunner/runners/QemuRunner.py
trunner/runners/__init__.py
trunner/runners/common.py
trunner/test_runner.py

- runner: add working imxrt117x runner (runner isn't available in default targets for now)
- runner: add ARMV7M7 class, common for imxrt106x and imxrt117x targets
- runner: move led method to device runner class
- runner: add status method for Runner class and restructure led control
- runner: adjust imxrt117x runner to MIMXRT1170 EVK
- tests: exclude running specific tests on imxrt117x target
It's needed for imxrt117x rack testing unit.

runner: add imxrt117x runner

---

socket/Makefile
socket/test_socket.c

JIRA: DTR-6
Socket tests for fixes from https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/228

posix: socket tests

---

waitpid/Makefile
waitpid/test.yaml
waitpid/test_waitpid.c

JIRA: PD-190
Failing test showing some problem with waitpid function

waitpid: add simple waitpid test

---

trunner/runners/IMXRT117xRunner.py

DONE: CI-112
- runner: imxrt117x: fix logfile in debug mode
DONE: CI-112

runner: imxrt117x: fix logfile in debug mode

---

psh/test-kill.py
psh/test.yaml
psh/tools/psh.py

JIRA: PD-77
- psh: add kill test
- There is also helper executable, which creates 3 while test processes in background (to kill) 
-  test to cover psh kill fixes in phoenix-rtos-kernel (https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/239)
I will merge this PR after phoenix-rtos-kernel fixes implementation

psh: add kill test and fix reading current target in psh test module

---

psh/test-echo.py
psh/test.yaml

JIRA: RTOS-156
Tests for psh applet `echo`
Tests regarding https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/119
- https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/119

psh: tests to `echo` psh app

---

libc/main.c
libc/string.c

JIRA: PD-189
Testing `strlcat` and `strlcpy` implementations
- https://github.com/phoenix-rtos/libphoenix/pull/164

string.h: strlcat() and strlcpy() tests

---

libc/main.c
libc/stdio_file.c

JIRA: CI-100
- Adding new tests of libc functions
- Testing file creation and access/permissions control of file related functions from `stdio.h`.
- Couple IGNORES used as some issues were found out
Issues regarding `stdio.h` file realted functions:
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/256
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/260
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/263
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/274
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/276
- https://github.com/phoenix-rtos/libphoenix/pull/163

tests-libc: add tests of file related functions from stdio.h

---

libc/main.c
libc/unistd_fsdir.c

JIRA: CI-100
- Adding tests for filesystem and directories related functions from unistd.h
- Multiple IGNOREs as multiple issues were found:
- All tests that pass are palced before IGNORE statement so they are checked even if whole test is ignored in the end
Issues regarding this PR:
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/280
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/287
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/288

test-libc: add tests of filesystem/directory functions from unistd.h

---

psh/test-ps.py

psh: test-ps: add support for /bin/psh parsing

---

libc/harness/Makefile
libc/harness/test-exec.py
libc/harness/test.yaml
libc/harness/test_exec.c
psh/test-ls-rootfs.py
psh/test-ls.py
psh/test.yaml
psh/tools/common.py
waitpid/Makefile
waitpid/test.yaml
waitpid/test_waitpid.c

- rename test_ls back to test-ls
- replace underscores with dashes in test executables run by test runner
Names of tests executables used by test runner should be name as follows: test-example
JIRA: PD-271

organize test names

---

libc/harness/test.yaml
libc/resolve_path.c
libc/test.yaml
meterfs/Makefile
meterfs/test_meterfs.yaml
psh/test.yaml
sample/helloworld/test.yaml
sample/test/test.yaml
trunner/builder.py
trunner/config.py
trunner/device.py
trunner/runners/ARMV7M7Runner.py
trunner/runners/HostRunner.py
trunner/runners/QemuRunner.py
trunner/test/test_config.py
waitpid/test.yaml

[JIRA: PP-17](https://jira.phoenix-rtos.com/browse/PP-17)
The test runner supports project `TARGET`s only (e.g. armv7m7-imxrt106x-project).
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/413

Adapt to projects build changes

---

unity/unity_config.h

…egers
Enables support for 64-Bit unsigned integers in Unity test framework.
Necessary for unit testing of  _libcache_ library which is currently under development.

unity: enable Unity support for 64-Bit integers

---

libuuid/Makefile
libuuid/generate.c
libuuid/main.c
libuuid/parse.c
libuuid/test.yaml

- libuuid: add unit tests
- Covering the implementation of libuuid functions
- JIRA: PD-289

libuuid: add unit tests

---

trunner/harnesses/factory.py
trunner/testcase.py

- trunner: return object instead of harness method by TestHarnessFactory
Returning only the harness method by `TestHarnessFactory` may be problematic, when using more functions.
DONE: PD-293

trunner: return object instead of harness method by TestHarnessFactory

---

psh/test-gibber.py
psh/test.yaml
psh/tools/README.md
psh/tools/psh.py

- psh: add assert_unprintable() to psh test module 
- psh: add test-gibber
JIRA: PD-77

psh: add gibber test

---

libcache/Makefile
libcache/libcache_utils.c
libcache/libcache_utils.h
libcache/test.yaml
libcache/test_libcache.c

Add tests of libcache library
JIRA: RTOS-204
https://github.com/phoenix-rtos/phoenix-rtos-corelibs/pull/21

Add libcache tests

---

meterfs/file_phx.c

meterfs: fix bug wrong operator used "." instead of "->"

---

psh/test-gibber.py

- psh: fix test-gibber
- Using sets mixes the order of printable characters in tested string so it may send `/abcxxxxxxx`. The `Unknown command` statement is expected (not `psh: abcxxxxxxx not found`) so now this string is sorted.
- JIRA: CI-148

psh: fix test-gibber

---

psh/test-history.py
psh/test.yaml
psh/tools/README.md
psh/tools/common.py
psh/tools/psh.py

- psh: add history test
- JIRA: PD-77

psh: add history test

---

socket/test_socket.c

socket: silent/fix compilation warnings

---

libc/common.h
libc/getpw.c
libc/pthread_cond.c
libc/pthread_cond_test_functions.c
libc/pthread_cond_test_functions.h
libc/resolve_path.c
libc/stdio_file.c
libc/string.c
libc/unistd_fsdir.c
libc/unistd_getopt.c
libc/wchar.c

This makes tests compilable on host (linux) and runnable (no SIGSEGV).
JIRA: CI-100

libc: fix programming mistakes

---

psh/test-ls-rootfs.py
psh/test-ls.py
psh/test-mkdir.py
psh/test-touch.py
psh/test.yaml
psh/tools/README.md
psh/tools/common.py
psh/tools/psh.py

- psh: add test-touch
- psh: simplify test-mkdir using functions common with test-touch
- JIRA: PD-77

psh: add test-touch

---

libc/stdio_file.c

- libc: stdio_file: fix fdopen_file case
- leaking filep2 in this test case
- JIRA: CI-149

libc: stdio_file: fix fdopen_file case

---

proc/test_priority.c
proc/test_thread_rand.c

JIRA: RTOS-226
Make tests compatible with fixed threadJoin.
- JIRA: RTOS-226

test: fix threadJoin call

---

libc/stdio_file.c

test-libc: cover clearerr and  fgetc changes

---

trunner/runners/common.py

trunner: correct erase timeout
JIRA: PD-328

trunner: correct erase timeout

---

psh/test-auth.py
psh/test-pshlogin.py

psh: pshlogin: assert prompt after exiting current session
psh: assert prompt every time after exiting auth
JIRA: PD-327

psh: test-pshlogin, test-auth fixes

---

psh/tools/psh.py

JIRA: PD-330
https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/166

psh: remove CR from prompt pattern

---

libc/Makefile
libc/common.h
libc/main.c
libc/test.yaml
libc/unistd_file.c
libc/unistd_uids.c

- libc: enable on dummyfs targets
- libc: temporary disable truncate/ftruncate up cases
- libc: adjust setpuids_setsid case in unistd_uids.c to dummyfs targets
- libc: create tmp and etc if didn't exist
- libc: increase stack size
- JIRA: PD-329

libc: enable test on dummyfs targets

---

psh/test-runfile.py
psh/test-touch-rootfs.py

psh: improve touch-rootfs test
psh: fix links case in runfile applet test
JIRA: CI-217

psh: fix links case in runfile applet test

---

thread-local/Makefile
thread-local/test.yaml
thread-local/tls.c
thread-local/tls_functions.c
thread-local/tls_functions.h

Create tests for thread-local storage
- JIRA: RTOS-209

test/thread-local: test thread local storage

---

thread-local/test.yaml

JIRA: RTOS-209
fixes test.yaml in thread-local test to be compatible with new runner

thread-local: fix test.yaml

---

libc/stdio_file.c

I've added the missing implementations of the [`fgetpos()` and `fsetpos()`](https://github.com/phoenix-rtos/libphoenix/pull/242) functions, and with this pull-request I add the basic tests for these functions (storing and restoring position).
JIRA: RTOS-392
https://github.com/phoenix-rtos/libphoenix/pull/242
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/655

libc: add fgetpos(), fsetpos() test

---

libc/main.c
libc/stdlib_alloc.c

Enabled malloc_usable_size funcion
Changed name of test group

libc:  alloc tests improvements

---

busybox/busybox.py
mbedtls/mbedtls.py
psh/test-runfile.py
psh/tools/psh.py
runner.py
trunner/__init__.py
trunner/config.py
trunner/ctx.py
trunner/extensions.py
trunner/harness/pyharness.py
trunner/harness/unity.py
trunner/host.py
trunner/target/armv7a9.py
trunner/target/armv7m4.py
trunner/target/emulated.py
trunner/target/host.py
trunner/test_runner.py
trunner/types.py

Add some improvement to the test runner. The main feature is defining custom arguments using flag "--kwarg" that can be used by extensions. Also now you can pass runner context as test argument. Messages of each commit describes the changes.

Add improvements to test runner.

---

libc/ctype.c
libc/main.c

Mateusz bloch/test ctype

---

runner.py
trunner/ctx.py
trunner/dut.py
trunner/test_runner.py

- trunner: add --logfile argument
- trunner: add printing logs for github-actions
JIRA: CI-224

trunner: add printing logs

---

libc/test.yaml

enable test-libc on armv7a9-zynq7000-qemu

---

libc/stdio_scanf.c

Uncommented the line of code in line 3641 which close connection with the file.
Unsolicited comment.

Fix fclose() in squareBrackets

---

trunner/target/armv7m4.py

trunner: pass not aligned size to plo alias cmd
JIRA: CI-276
It's not needed, applied after the corresponding change in plo scripts used in project (https://github.com/phoenix-rtos/phoenix-rtos-project/commit/fb5e36f8cb0a80cb12e4e154ca9883bd0093d18a)

trunner: pass not aligned size to plo alias cmd

---

libc/main.c
libc/signal.c
libc/string_errsig.c

Mateusz bloch/test strerror strsignal

---

libc/main.c
libc/stdio_printf.c

mateusz-bloch/libc: printf tests

---

Makefile.host
libc/main.c
libc/printf/Makefile
libc/printf/stdio_printf.c
libc/printf/test.yaml

move printf test

---

busybox/test_busybox.yaml

Mateusz bloch/busybox: enable tests

---

libc/main.c
libc/stdlib_bsearch.c

libc: add bsearch test

---

libc/string/main.c
libc/string/string_catdup.c
libc/testdata.c
libc/testdata.h

added tests for strcat, strncat, strdup, strndup
JIRA CI-233

mateusz-bloch/libc: add tests for strcat(), strdup()

---

libc/misc/resolve_path.c

libc: resolvepath test improvments

---

libc/Makefile

libc: increase stack size

---

libc/misc/main.c
libc/misc/stat.c

Added tests for stat, fstat, lstat
JIRA CI-236

Mateusz bloch/test stat

---

libc/misc/stat.c

libc: enable additional test cases in the stat test

---

requirements.txt
trunner/text.py

trunner: enable colorful logs

---

psh/test-ls-rootfs.py
psh/tools/common.py

psh: fix expected regex in size case for test-ls-rootfs

---

busybox/test_busybox.yaml

busybox: enable ignored tests

---

trunner/harness/__init__.py
trunner/harness/plo.py
trunner/target/armv7a7.py
trunner/target/armv7a9.py
trunner/target/armv7m7.py
trunner/target/base.py

trunner: switch to jjfs2 on zynq7000

---

requirements.txt

requirements: update PyYAML

---

psh/tools/README.md
psh/tools/psh.py

psh: improve check psh

---

busybox/test_busybox.yaml
libc/misc/ctype.c
libc/string/string_errsig.c

tests: enable ignored tests

---

.github/workflows/runner-ci.yaml

ci: add problem matcher for flake8 errors and update checked python version

---

Makefile
Makefile.sparcv8leon3
devices/gr716-multi/Makefile
devices/gr716-multi/test-gr716-multi.c
devices/gr716-multi/test.yaml

JIRA: RTOS-534
- add `devices` directory for `phoenix-rtos-devices` tests
- add tests for `gr716-multi` driver

devices: add tests for gr716-multi

---

virtio/test_virtio.c

test_virtio: fix target define

---

ioctl/test-ioctl.c
proc/test_msg.c

Adapt to msgRecv, msgRespond API change

---

mbedtls/test.yaml

https://github.com/phoenix-rtos/phoenix-rtos-project/issues/829

mbedtls: disable test_suite_mpi

---

psh/tools/psh.py

Inroduced to avoid issue #866
JIRA: CI-354

psh: disable executing tests in new psh for imxrt117x

---

psh/test-ls-rootfs.py
psh/test-ls.py
psh/test-mkdir.py
psh/tools/common.py

psh: add removing test files and directories

---

libc/pthread/pthread_cond.c

pthread: Fix pthread_condattr_setclock test

---

psh/tools/common.py

psh: avoid SH syntax in test strings

---

trunner/tools/phoenix.py

trunner: introduce a timeout after finding plo device

---

libc/misc/unistd_file.c
libc/misc/unistd_uids.c

libc: misc: re-enable test cases

---

mbedtls/test.yaml

mbedtls: disable test_suite_rsa

---

psh/tools/psh.py

Add additional (psh)% assert after date command to avoid overlap from next command.
JIRA: CI-371

Trunner: fix psh date assert for armv7m4

---

trunner/target/armv7m4.py

Trunner: stm32l4x6 remove workaround serial dut

---

trunner/target/armv7a9.py

changed name of used file to upload PLO via JLink

trunner: change using gdb file to upload via jlink

---

trunner/target/armv7a9.py
trunner/target/armv7m4.py
trunner/tools/gdb.py

Changing way that plo is loaded to board using onboard jtag chip.
JIRA: CI-364
- https://github.com/phoenix-rtos/phoenix-rtos-build/pull/166

trunner: armv7a9: change way that plo is loaded to board

---

disk/test_disk.c
mem/test_mmap.c
proc/test_msg.c

JIRA: RTOS-665
Adjust mmap to POSIX standard.
https://github.com/phoenix-rtos/libphoenix/pull/306

Adjust mmap calls to new interface

---

trunner/config.py
trunner/target/armv7m4.py
trunner/target/armv7m7.py
trunner/target/base.py
trunner/target/host.py
trunner/tools/gdb.py
trunner/tools/phoenix.py
trunner/types.py

trunner: yaml add absolute path support in execute parameter

---

trunner/harness/plo.py
trunner/target/armv7a7.py
trunner/target/armv7a9.py

trunner: plo: force to pass block erase timeout

---

trunner/target/armv7a9.py
trunner/tools/__init__.py

armv7a9: Waiting for ftdi device

---

libc/misc/unistd_file.c

casting to off_t was performed after negating the value. size_t is uint64_t on host, so 1 --(negate unsigned)--> 0xffffffffffffffffU --(cast to off_t)--> -1, but on 32 bit target 1 --(negate unsigned)--> 0xffffffffU --(cast to off_t)--> 4294967289
Enabled errno tests on phoenix
JIRA: RTOS-397
tested in: https://github.com/phoenix-rtos/phoenix-rtos-project/pull/939
fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/360

lseek: Fix test setting big positive offset instead of negative

---

trunner/target/armv7a9.py

trunner: zynq7000: remove expecting wait before flashing

---

Makefile
Makefile.sparcv8leon3
devices/gr716-multi/test.yaml
devices/grlib-multi/Makefile
devices/grlib-multi/test-grlib-multi.c
devices/grlib-multi/test.yaml

JIRA: RTOS-704
- rename files to match renamed driver name
- fixes in message preparation
- run GPIO tests only on GR716-MINI
- remove checking if pins were set correctly through `platformctl` - this does not make sense on targets there is no I/O mux (GR716 on FPGA) or pins are set automatically (GR712RC) - given that we do not have GR716-MINI I've decided to remove this checks

devices/gr716-multi: rename to grlib-multi, fix to work with GR712RC

---

psh/tools/psh.py
trunner/harness/psh.py
trunner/target/armv7m4.py

Disabling dmesg output until test campaign are done
JIRA: CI-393

trunner: mute dmesg while truner lasts

---

psh/tools/common.py

psh: avoid `'" in psh tests

---

devices/grlib-multi/test-grlib-multi.c

devices/grlib-multi: add tests for SpaceWire

---

devices/grlib-multi/test-grlib-multi.c
fs/test_fcntl.c

update installed headers include path

---

ioctl/Makefile
libc/Makefile

libc: disable built-in optimizations

---

mem/test.yaml

mem: disable test-mprotect-fault because of an issue

---

trunner/harness/base.py
trunner/harness/unity.py

adamdebek/ci 406/407

---

libc/test.yaml
psh/test.yaml
trunner/target/emulated.py

phoenix-rtos/phoenix-rtos-kernel/pull/502

enable most of the tests on riscv64-qemu

---

libc/misc/stat.c

libc: stat: enable fifo_type test case

---

micropython/micropython_repl.py
micropython/test_repl.yaml

micropython: fix REPL harness

---

libc/scanf/stdio_scanf.c

JIRA: CI-410
Fixing and provide execution of missed ranges test of square Brackets group.

libc: scanf: fixing squareBrackets ranges

---

psh/test-kill.py

JIRA: CI-415
Nedded for  https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/215

psh: make test-kill more flexible

---

libc/misc/stat.c

libc: stat: enable fifo_type test case on stm32

---

libc/socket/unix-socket.c
libc/test.yaml

libc: unix-socket: separate test cases

---

devices/grlib-multi/test-grlib-multi.c
meterfs/file_phx.c
proc/test_msg.c

msg API changes

---

devices/grlib-multi/test-grlib-multi.c

test-grlib-multi: fix warning

---

meterfs/Makefile

host-flash/meterfs: Add libtinyaes

---

trunner/target/armv7a7.py

trunner: adjust imx6ull soft reset time

---

busybox/test_busybox.yaml

busybox: enable tests on armv7a7-imx6ull

---

devices/grlib-multi/test-grlib-multi.c
ioctl/test-ioctl.c
libc/exit/exit.c
libc/math/main.c
libc/misc/main.c
libc/printf/stdio_printf.c
libc/pthread/main.c
libc/scanf/stdio_scanf.c
libc/socket/inet-socket.c
libc/socket/unix-socket.c
libc/stdio/main.c
libc/stdlib/main.c
libc/string/main.c
libc/test.yaml
libcache/test_libcache.c
libuuid/main.c
mem/test_mprotect.c
mem/test_mprotect_fault.c
meterfs/test_meterfs_allocate.c
meterfs/test_meterfs_miscellaneous.c
meterfs/test_meterfs_openclose.c
meterfs/test_meterfs_writeread.c
proc/test_thread_rand.c
sample/test/fails/test-fail-unity-exc.c
sample/test/fails/test-fail-unity.c
sample/test/test-unity.c
setjmp/setjmp.c
thread-local/tls.c
waitpid/test_waitpid.c

unity tests: return non zero exit code when test failed

---

requirements.txt

Also: remove non-direct dependencies, bump some of the versions.
JIRA: CI-451

trunner: requirements: install RPi.GPIO only on ARM targets

---

psh/test-ps.py

JIRA: CI-455
Flexible alternative for https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/353#pullrequestreview-2096712711

psh: support both [idle] and [kthread] in ps test

---

psh/tools/psh.py

psh: ensure that deinit is always executed

---

devices/grlib-multi/test-grlib-multi.c

test-grlib-multi: name union in platformctl_t

---

sys/Makefile
sys/cond/cond.c
sys/mutex/mutex.c
sys/test.yaml

With the introduction of attributes for condvars/mutexes I've decided to also create related tests for them.
I'm open for suggestions regarding location in the repo (considered also creating `sys` directory in `libc`).
Tested on CI: https://github.com/phoenix-rtos/phoenix-rtos-project/pull/1113

sys: implement tests for native mutex and cond API

---

trunner/harness/unity.py

unity: add handling fails without message in harness

---

psh/tools/psh.py
trunner/harness/psh.py

psh/trunner: fix wrong message in case of failing

---

mem/Makefile
mem/test.yaml
mem/test_mmap_new.c

mmap: add test for unaligned len

---

psh/test-runfile.py

psh: delete devices test case in runfile test

---

trunner/target/armv7a9.py

JIRA: CI-521
Adds omitted clear_buffer to prevent caching output from previous step in to another one. This situation occurs only on start of campaign when step `Flash` is present. Excessive output is connected with changing state of device from loading image to launching it.

trunner: armv7a9: add missing clear_buffer

---

proc/test_priority.c

proc/test_priority: increase stack sizes, join threads based on tids

---

libc/socket/unix-socket.c

JIRA: CI-527
Cleanup test environment

libc/socket: unlink socket files after test end

---

libc/stdio/stdio_file.c

libc/stdio/file: fix and enable ignored tests

---

libc/signal/handler.c

libc: add testcase covering #1232 issue

---

trunner/target/armv8m33.py

According to discussion in: https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/400#discussion_r2225854365
This assert makes it impossible to run tests without interactive shell.
JIRA: CI-553

armv8m33: remove assert after flash

---

requirements.txt

The RPi.GPIO library does not support the Raspberry Pi 5. Instead, the rpi-lgpio library is used to ensure compatibility with both Raspberry Pi 4 and 5.
JIRA: CI-572

requirements: change RPI.GPiO to rpi-lgpio

---

coremark_pro/coremark_pro.py
coremark_pro/test_coremark_pro.yaml
coremark_pro/timeouts.yaml

JIRA: CI-563
- https://github.com/phoenix-rtos/phoenix-rtos-ports/pull/113
- https://github.com/phoenix-rtos/phoenix-rtos-project/pull/1333

coremark_pro: add performance tests
